name: StayFloripa
description: "Casas familiares em Florianopolis."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  date_field: ^2.1.2
  syncfusion_flutter_charts: ^20.3.58
  flutter_hooks: ^0.18.6
  localstore: ^1.3.5
  salomon_bottom_bar: ^3.3.2
  flutter_neat_and_clean_calendar: ^0.3.13+28
  google_fonts: ^5.0.0
  flutter_slidable: ^3.0.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/